name: LogNormDistr CI

on:
   push:
      branches: [ main, develop ]
   pull_request:
      branches: [ main, develop ]

jobs:
   validation:
      name: Validation
      runs-on: macos-latest
      steps:
         -  uses: actions/checkout@v3
         -  uses: gradle/wrapper-validation-action@v1

   build-test:
      name: Build test
      runs-on: macos-latest
      steps:
         -  uses: actions/checkout@v3
         -  uses: actions/setup-java@v3
            with:
               java-version: 18
               distribution: 'zulu'
         -  uses: gradle/gradle-build-action@v2
         -  run: ./gradlew build --stacktrace

   run-unit-tests:
      name: Unit tests
      runs-on: macos-latest
      steps:
         -  uses: actions/checkout@v3
         -  uses: actions/setup-java@v3
            with:
               java-version: 18
               distribution: 'zulu'
         -  uses: gradle/gradle-build-action@v2
         -  run: chmod +x gradlew
         -  run: ./gradlew test

   detekt:
      name: Detekt
      runs-on: macos-latest
      steps:
         -  uses: actions/checkout@v3
         -  uses: actions/setup-java@v3
            with:
               java-version: 18
               distribution: 'zulu'
         -  uses: gradle/gradle-build-action@v2
         -  run: ./gradlew detekt

   instrumentation-tests:
      name: Instrumentation tests
      runs-on: macos-latest
      steps:
         -  uses: actions/checkout@v3
         -  uses: actions/setup-java@v3
            with:
               java-version: 11
               distribution: 'adopt'
               cache: 'gradle'
         -  uses: ReactiveCircus/android-emulator-runner@v2
            with:
               api-level: 31
               target: google_apis
               arch: x86_64
               script: ./gradlew connectedCheck --scan --stacktrace